BlackJack Online Game/ProjectBlackjack/Controllers/BlackJackController.cs
using ProjectBlackjack.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace ProjectBlackjack.Controllers
{
    public class BlackJackController : Controller
    {
        // GET: BlackJack
        public ActionResult Index()
        {
            InitializeDeckDesign(0);
            InitializeDeck();
            ShuffleDeck();
            CreatePlayer();
            CreateDealer();
            return View((List < Card >)Session["CardDeckDemo"]);
        }

        [HttpPost]
        public ActionResult Index(int deckDesignPassed)
        {
            ReInitializeDeckDesign(deckDesignPassed);
            //InitializeDeck();
            //ShuffleDeck();
            return View((List<Card>)Session["CardDeckDemo"]);
        }

        //public ActionResult Index2()
        //{
        //    return View((List<Card>)Session["CardDeck"]);
        //}

        [NonAction]
        public void InitializeDeckDesign(int value)
        {
            DeckDesign deckDesign = new DeckDesign()
            { DesignType = (DeckDesign.DesignTypeEnum)Enum.Parse(typeof(DeckDesign.DesignTypeEnum), value.ToString()) };

            Session["DeckDesign"] = deckDesign;
        }

        [NonAction]
        public void ReInitializeDeckDesign(int value)
        {
            DeckDesign deckDesign = new DeckDesign()
            { DesignType = (DeckDesign.DesignTypeEnum)Enum.Parse(typeof(DeckDesign.DesignTypeEnum), value.ToString()) };

            Session["DeckDesign"] = deckDesign;
            IList<Card> cardDeck = (List<Card>)Session["CardDeck"];
            IList<Card> cardDeckDemo = (List<Card>)Session["CardDeckDemo"];
            foreach (Card card in cardDeck)
            {
                card.ImagePath = ((DeckDesign)Session["DeckDesign"]).DesignFolderPath;
            }
            foreach (Card cardDemo in cardDeckDemo)
            {
                cardDemo.ImagePath = ((DeckDesign)Session["DeckDesign"]).DesignFolderPath;
            }
            Session["CardDeck"] = cardDeck;
            Session["CardDeckDemo"] = cardDeckDemo;
        }


        [NonAction]
        public void InitializeDeck()
        {
            IList<Card> cardDeck = new List<Card>();
            IList<Card> cardDeckDemo = new List<Card>();
            for (int i = 0; i < 52; i++)
            {
                cardDeck.Add(new Card() { Position = i, ImagePath = ((DeckDesign)Session["DeckDesign"]).DesignFolderPath });
                cardDeckDemo.Add(new Card() { Position = i, ImagePath = ((DeckDesign)Session["DeckDesign"]).DesignFolderPath });
            }
            Session["CardDeck"] = cardDeck;
            Session["CardDeckDemo"] = cardDeckDemo;
        }

        [NonAction]
        public void ShuffleDeck()
        {
            //  from wikipedia:
            //  http://en.wikipedia.org/wiki/Fisher-Yates_shuffle
            Random rand = new Random();
            IList<Card> cardDeck = (List<Card>)Session["CardDeck"];
            for (int i = cardDeck.Count - 1; i > 0 ; i--)
            {
                int randomPosition = rand.Next(i+1);
                Card tempCard = cardDeck[i];
                cardDeck[i] = cardDeck[randomPosition];
                cardDeck[randomPosition] = tempCard;
            }
            Session["CardDeck"] = cardDeck;
        }

        // GET: BlackJack/Play
        public ActionResult Play()
        {
            if (Session["CardDeck"] is null)
            {
                return RedirectToAction("Index");
            }
            Player dealer = (Player)Session["Dealer"];
            Player player = (Player)Session["Player"];
            player.Hand = new Hand();
            player.Hand.AllCards = new List<Card>();
            dealer.Hand = new Hand();
            dealer.Hand.AllCards = new List<Card>();
            Session["Dealer"] = dealer;
            Session["Player"] = player;
            Session["Winner"] = "Empty";
            return View((Player)Session["Player"]);
        }

        [NonAction]
        public void CreatePlayer()
        {
            Player player = new Player();
            player.Account = 500;
            player.Bet = 0;
            player.Hand = new Hand();
            player.Hand.AllCards = new List<Card>();
            
            Session["Player"] = player;
        }

        [NonAction]
        public void CreateDealer()
        {
            Player dealer = new Player();
            //dealer.Account = new Balance();
            //dealer.Bet = new Balance();
            dealer.Hand = new Hand();
            dealer.Hand.AllCards = new List<Card>();
            Session["Dealer"] = dealer;
        }

        [HttpGet]
        public PartialViewResult AjaxPlayerHit()
        {
            Player player = (Player)Session["Player"];
            if (player.Hand.End)
            {
                return PartialView("Empty");
            }

            if ( ((List<Card>)Session["CardDeck"]).Count < 11 )
            {
                InitializeDeck();
                ShuffleDeck();
            }
            IList<Card> cardDeck = (List<Card>)Session["CardDeck"];

            
            Card newCard = cardDeck.FirstOrDefault();
            player.Hand.AddCard = newCard;
            cardDeck.Remove(newCard);

            player.ShowBusted = player.Hand.IsBusted;
            player.ShowBlackJack = player.Hand.IsBlackJack;

            Session["CardDeck"] = cardDeck;
            Session["Player"] = player;

            return PartialView("AjaxAddCard", newCard);
        }

        [HttpGet]
        public PartialViewResult AjaxDealerHit()
        {
            Player dealer = (Player)Session["Dealer"];
            Player player = (Player)Session["Player"];
            if (dealer.Hand.End)
            {
                return PartialView("Empty");
            }
            if ((!player.Hand.End) && (dealer.Hand.AllCards.Count>=1))
            {
                return PartialView("Empty");
            }

            if (((List<Card>)Session["CardDeck"]).Count < 11)
            {
                InitializeDeck();
                ShuffleDeck();
            }

            IList<Card> cardDeck = (List<Card>)Session["CardDeck"];


            Card newCard = cardDeck.FirstOrDefault();
            dealer.Hand.AddCard = newCard;
            cardDeck.Remove(newCard);

            dealer.ShowBusted = dealer.Hand.IsBusted;
            dealer.ShowBlackJack = dealer.Hand.IsBlackJack;

            if (dealer.Hand.IsSeventeen)
            {
                dealer.Hand.End = true;
            }
            if ((player.Hand.IsBusted) && (dealer.Hand.AllCards.Count > 1))
            {
                dealer.Hand.End = true;
            }

            if ((player.Hand.End) && (dealer.Hand.End) )
            {
                CalculateWinner();
            }

            Session["CardDeck"] = cardDeck;
            Session["Dealer"] = dealer;

            return PartialView("AjaxAddCard", newCard);
        }

        [NonAction]
        public void CalculateWinner()
        {
            Player dealer = (Player)Session["Dealer"];
            Player player = (Player)Session["Player"];
            if (player.Hand.IsBlackJack && !dealer.Hand.IsBlackJack)
            {
                Session["Winner"] = "You Win!";
                player.Account += (int)(2.5 * ((double)player.Bet));
                player.Bet = 0;
                Session["Player"] = player;
                Session["Dealer"] = dealer;
                return;
            }
            if (player.Hand.IsBlackJack && dealer.Hand.IsBlackJack)
            {
                Session["Winner"] = "You Lose!";
                player.Bet = 0;
                Session["Player"] = player;
                Session["Dealer"] = dealer;
                return;
            }
            if (!player.Hand.IsBlackJack && dealer.Hand.IsBlackJack)
            {
                Session["Winner"] = "You Lose!";
                player.Bet = 0;
                Session["Player"] = player;
                Session["Dealer"] = dealer;
                return;
            }
            if (!player.Hand.IsBusted && dealer.Hand.IsBusted)
            {
                Session["Winner"] = "You Win!";
                player.Account += (2 * (player.Bet));
                player.Bet = 0;
                Session["Player"] = player;
                Session["Dealer"] = dealer;
                return;
            }
            if (player.Hand.IsBusted && dealer.Hand.IsBusted)
            {
                Session["Winner"] = "Push";
                player.Account += player.Bet;
                player.Bet = 0;
                Session["Player"] = player;
                Session["Dealer"] = dealer;
                return;
            }
            if (player.Hand.IsBusted && !dealer.Hand.IsBusted)
            {
                Session["Winner"] = "You Lose!";
                player.Bet = 0;
                Session["Player"] = player;
                Session["Dealer"] = dealer;
                return;
            }
            if (player.Hand.FinalPoints > dealer.Hand.FinalPoints)
            {
                Session["Winner"] = "You Win!";
                player.Account += (2 * (player.Bet));
                player.Bet = 0;
                Session["Player"] = player;
                Session["Dealer"] = dealer;
                return;
            }
            if (player.Hand.FinalPoints == dealer.Hand.FinalPoints)
            {
                Session["Winner"] = "Push";
                player.Account += player.Bet;
                player.Bet = 0;
                Session["Player"] = player;
                Session["Dealer"] = dealer;
                return;
            }
            if (player.Hand.FinalPoints < dealer.Hand.FinalPoints)
            {
                Session["Winner"] = "You Lose!";
                player.Bet = 0;

BlackJack Online Game/ProjectBlackjack/Views/BlackJack/AjaxAddCard.cshtml
@model ProjectBlackjack.Models.Card



<div class=" col-1 cardsize" style="position: relative;z-index:1040" >
    <div class="frontCard animated flipfront " style="position: absolute;   left: 0;  top: 0;backface-visibility: hidden;align-items: center;justify-content: center;display: flex;">
        <img src=@Html.DisplayFor(model => model.ImagePath)
             alt="@Html.DisplayFor(model => model.CardName) of @Html.DisplayFor(model => model.Suit)"
             title="@Html.DisplayFor(model => model.CardName) of @Html.DisplayFor(model => model.Suit)"
             class="cardsize"
             style="padding:0;" />
    </div>
    <div class="backCard animated flipback " style="transform: rotateY(180deg);position: absolute;   left: 0;  top: 0;backface-visibility: hidden;align-items: center;justify-content: center;display: flex;">
        <img src="/Content/Images/Standard/back.png"
             alt="card"
             title="card"
             class="cardsize"
             style="padding:0;" />
    </div>
</div>

BlackJack Online Game/ProjectBlackjack/Views/BlackJack/AjaxGetWinner.cshtml
@model string
@using ProjectBlackjack.Models;

<h3>Final Message: </h3>
<br />
<input type="text" id="GetWinnerMessageTextBox" value="@Model" disabled="disabled" />
<br />

BlackJack Online Game/ProjectBlackjack/Views/BlackJack/AjaxUpdateDealerInfo.cshtml
@model ProjectBlackjack.Models.Player
@using ProjectBlackjack.Models;

<h3>Dealer Info: </h3>
FinalPoints:
<br />
<input type="text" id="DealerFinalPointsTextBox" value="@Model.Hand.FinalPoints" disabled="disabled" />
<br />
IsBusted:
<br />
<input type="checkbox" id="DealerIsBustedCheckBox" checked="@Model.Hand.IsBusted" />
<br />
ShowBusted:
<br />
<input type="checkbox" id="DealerShowBustedCheckBox" checked="@Model.ShowBusted" />
<br />
IsBlaskJack:
<br />
<input type="checkbox" id="DealerIsBlackJackCheckBox" checked="@Model.Hand.IsBlackJack" />
<br />
ShowBlackJack:
<br />
<input type="checkbox" id="DealerShowBlackJackCheckBox" checked="@Model.ShowBlackJack" />
<br />
End:
<br />
<input type="checkbox" id="DealerEndCheckBox" checked="@Model.Hand.End" />
<br />
IsSeventeen:
<br />
<input type="checkbox" id="DealerIsSeventeenCheckBox" checked="@Model.Hand.IsSeventeen" />
<br />

@{
    ((Player)Session["Dealer"]).ShowBusted = false;
    ((Player)Session["Dealer"]).ShowBlackJack = false;
}

BlackJack Online Game/ProjectBlackjack/Views/BlackJack/AjaxUpdatePlayerInfo.cshtml
@model ProjectBlackjack.Models.Player
@using ProjectBlackjack.Models;

<h3>Player Info: </h3>
FinalPoints:
<br />
<input type="text" id="PlayerFinalPointsTextBox" value="@Model.Hand.FinalPoints" disabled="disabled" />
<br />
IsBusted:
<br />
<input type="checkbox" id="PlayerIsBustedCheckBox" checked="@Model.Hand.IsBusted" />
<br />
ShowBusted:
<br />
<input type="checkbox" id="PlayerShowBustedCheckBox" checked="@Model.ShowBusted" />
<br />
IsBlaskJack:
<br />
<input type="checkbox" id="PlayerIsBlackJackCheckBox" checked="@Model.Hand.IsBlackJack" />
<br />
ShowBlackJack:
<br />
<input type="checkbox" id="PlayerShowBlackJackCheckBox" checked="@Model.ShowBlackJack" />
<br />
End:
<br />
<input type="checkbox" id="PlayerEndCheckBox" checked="@Model.Hand.End" />
<br />
IsSeventeen:
<br />
<input type="checkbox" id="PlayerIsSeventeenCheckBox" checked="@Model.Hand.IsSeventeen" />
<br />
AccountAmount:
<br />
<input type="number" id="PlayerAccountAmountTextBox" value="@Model.Account" disabled="disabled" />
<br />
BetAmount:
<br />
<input type="number" id="PlayerBetAmountTextBox" value="@Model.Bet" disabled="disabled" />
<br />

@{
    ((Player)Session["Player"]).ShowBusted = false;
    ((Player)Session["Player"]).ShowBlackJack = false;
}

BlackJack Online Game/ProjectBlackjack/Views/BlackJack/Index.cshtml
@model IEnumerable<ProjectBlackjack.Models.Card>
@using ProjectBlackjack.Models;

@section scripts
{
    <script>
        $("document").ready(function () {
            $('#DropDownListDesignType').val(@((int)(((DeckDesign)Session["DeckDesign"]).DesignType)));
            $('#DropDownListDesignType').on("change", function () {
                var deckDesign = $('#DropDownListDesignType').val();
                $('#deckDesignPassed').val(deckDesign);
                $("#deckDesignPassedForm").submit();
            });
        });



    </script>
}

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="row">
        <h1 style="color:white;margin:30px;">BLACKJACK</h1>



        <form id="deckDesignPassedForm" method="POST">
            <input type="text" id="deckDesignPassed" name="deckDesignPassed" hidden="hidden" />


            <h2 style="color:white;margin:30px;">Select your cards</h2>
            @Html.DropDownList("DropDownListDesignType",
            EnumHelper.GetSelectList(typeof(DeckDesign.DesignTypeEnum)) ,
            new { @class = " btn btn-secondary dropdown-toggle" , style = "margin:20px;" })


            <h2 style="color:white;margin:30px;">Play the Game</h2>
            @Html.ActionLink("Play Now!", "Play", "BlackJack", null, new { @class = "btn btn-danger align-middle", id = "PlayAgainButton", style = " margin: 50px; height: 40px;width: 80px;display:table-cell;vertical-align:middle;display: inline;" })
        </form>

    </div>

        <div class="row">
            @foreach (var item in Model)
            {
                <div class="animated fadeIn col-2 " style="margin:30px;">
                    <img src=@Html.DisplayFor(modelItem => item.ImagePath)
                         alt="@Html.DisplayFor(modelItem => item.CardName) of @Html.DisplayFor(modelItem => item.Suit)"
                         title="@Html.DisplayFor(modelItem => item.CardName) of @Html.DisplayFor(modelItem => item.Suit)"
                         height="250" />
                </div>
            }

        </div>

BlackJack Online Game/ProjectBlackjack/Views/BlackJack/Index2.cshtml
@model IEnumerable<ProjectBlackjack.Models.Card>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAce)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Suit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAce)
        </td>
        <td>
            <img src=@Html.DisplayFor(modelItem => item.ImagePath) alt="" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>